name: flowscores
description: A piano sheet manager with PDF/scan + metronome
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # File import / camera
  file_picker: ^8.0.3
  image_picker: ^1.0.7

  # Viewers
  flutter_cached_pdfview: ^0.4.3
  photo_view: ^0.15.0

  # Metronome (player pool approach)
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    # IMPORTANT: exact case must match the real file name you said you changed to
    - assets/click.MP3
